apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jfernando12/tdg-auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auths'
            - name: ROOT_ID
              valueFrom:
                secretKeyRef:
                  name: root-id-secret
                  key: ROOT_ID
            - name: ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: root-username-secret
                  key: ROOT_USERNAME
            - name: ROOT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: root-email-secret
                  key: ROOT_EMAIL
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-password-secret
                  key: ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
