apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        - name: images
          image: jfernando12/tdg-images
          env:
            - name: MONGO_URI
              value: 'mongodb://images-mongo-srv:27017/images'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-bucket-name-secret
                  key: AWS_BUCKET_NAME
            - name: AWS_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-bucket-region-secret
                  key: AWS_BUCKET_REGION
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key-secret
                  key: AWS_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: images-srv
spec:
  selector:
    app: images
  ports:
    - name: images
      protocol: TCP
      port: 3000
      targetPort: 3000
